Contributors API service by Web Crawler
fga-eps-mds/2019.1-hubcare-api pull request #96
Opened 2019-06-03 20:11 UTC by Hiroshi18

## Issue #89 

## Description
We 

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2019-06-04 02:19 UTC, filipetoyoshima requested changes
![image](https://user-images.githubusercontent.com/29482983/58846417-800a1f80-8655-11e9-820f-52de079edf7d.png)

I've runned:
```bash
find . -name "*.sqlite3" -type f -delete
export TOKEN='<my token>'
export NAME='filipetoyoshima'
docker-compose up --build
```

2019-06-04 17:59 UTC, Hiroshi18 commented
It must be called from the gateway

2019-06-04 18:02 UTC, Hiroshi18 commented
I believe none of the app's can be tested this way since the refactoring of the project

2019-06-04 21:42 UTC, RomuloSouza commented
If the problem is the query on get method, you can simply add the following line at the beginning of the method:
Return Response('test')
This way you can call the post method through the django rest interface

2019-06-04 23:49 UTC, filipetoyoshima requested changes
![image](https://user-images.githubusercontent.com/29482983/58920825-3f201280-870a-11e9-9608-e436f6bc0af8.png)

2019-06-05 00:07 UTC, filipetoyoshima commented
I would like to say that is a corner case problem, but no:

![image](https://user-images.githubusercontent.com/29482983/58921380-bfe00e00-870c-11e9-852d-bb6aea4799ac.png)

2019-06-07 14:09 UTC, RomuloSouza requested changes

2019-06-07 14:09 UTC, RomuloSouza commented on hubcare/metrics/commit_metrics/contributors/views.py
>              'https://api.github.com/repos/' + owner + '/' + repo + '/commits',
I suppose you this url isn't correct. This request returns only the last 30 commits. You should use the tag per_page=100 to get the last 100 commits, and if this does not solve the problem of 4 different conttributors, you should verify if there are more pages.

2019-06-08 01:05 UTC, cjjcastro requested changes
Please solve the conflicts

2019-06-08 17:52 UTC, Hiroshi18 commented on hubcare/metrics/commit_metrics/contributors/views.py
>              'https://api.github.com/repos/' + owner + '/' + repo + '/commits',
Alright will see it

2019-06-11 00:21 UTC, Hiroshi18 commented
> Please solve the conflicts

Ok did it now

2019-06-11 00:39 UTC, Hiroshi18 commented
He is back for another round...

Found a bug in the activity rate will try to fix

![DeepinScreenshot_select-area_20190610213817](https://user-images.githubusercontent.com/26282955/59235535-2ca14f80-8bc8-11e9-9136-fda7d7237f15.png)

2019-06-11 00:45 UTC, Hiroshi18 commented
Think it is fixed

2019-06-11 03:14 UTC, filipetoyoshima commented
That was a long fight

2019-06-11 03:28 UTC, filipetoyoshima requested changes
And looks like the fight isn't over yet.
![image](https://user-images.githubusercontent.com/29482983/59241841-9c6f0480-8bdf-11e9-83ee-b0c531501ec3.png)

`nodejs/node` works finnely.
`filipetoyoshima/test` attacks again.

2019-06-11 13:13 UTC, filipetoyoshima approved these changes
Well... I really dunno explain what happened, but I've tested again and it worked.
Computer Science is not an exact science, surely it is more like witchcraft or sorcery.

It is ok and pretty fast.

2019-06-11 13:14 UTC, merged